version: '3'
services:
  blc:
    image: "shesek/lightning-charge:0.4.23"
    environment:
      - API_TOKEN=mySecretToken
    volumes:
      - blc:/data
  api-server:
    build: server
    depends_on:
      - blc
    links:
      - blc
    environment:
      - CHARGE_ROOT=http://api-token:mySecretToken@blc:9112
      - CALLBACK_URI_ROOT=http://localhost:9292
      - CHARGE_API_TOKEN=mySecretToken
      - ENV=development
      - REDIS_URI=redis://redis:6379
    volumes:
      - data:/data
  tx-daemon:
    build: server
    depends_on:
      - api-server
      - redis
    links:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379
      - ENV=development
    volumes:
      - data:/data
    command: daemon.sh
  sse-server:
    build:
      context: sse/
    depends_on:
      - api-server
      - redis
    links:
      - redis
    environment:
      - SUB_CHANNELS=transmissions
      - REDIS_URI=redis://redis:6379
  redis:
    image: "redis:latest"
  proxy_server:
    image: proxy_server
    build: nginx
    depends_on:
      - api-server
      - sse-server
    ports:
      - 8080:80

volumes:
  blc:
  data:
