development:
  adapter: sqlite3
  database: /data/ionosphere/ionosphere_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: /tmp/ionosphere_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: /data/ionosphere/ionosphere_production.sqlite3
  pool: 5
  timeout: 5000
