development:
  adapter: sqlite3
  database: /data/satellite-api/db_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: /tmp/satellite_api_test_db.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: /data/satellite-api/db_production.sqlite3
  pool: 5
  timeout: 5000
